# Generated by Django 6.0 on 2026-02-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_mappin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappin',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mappin',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
