# Generated by Django 6.0 on 2026-01-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='title',
        ),
    ]
