# Generated by Django 6.0 on 2026-02-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_remove_schedule_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
