# Generated by Django 6.0 on 2026-02-28 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_pintype_destination_pin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappin',
            name='pin_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_pins', to='destinations.pintype'),
        ),
    ]
