# Generated by Django 6.0 on 2026-03-01 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_mappin_pin_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='pin_type',
        ),
        migrations.RemoveField(
            model_name='mappin',
            name='pin_type',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='PinType',
        ),
    ]
