# Generated by Django 6.0 on 2026-03-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_remove_destination_pin_type_remove_mappin_pin_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='admission_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='admission_fee',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='destination',
            name='parking_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='parking_fee',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
