# Generated by Django 6.0 on 2026-04-08 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_destination_admission_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='selected_pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='destinations.mappin'),
        ),
    ]
