# Generated by Django 6.0 on 2026-04-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0008_destination_selected_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappin',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
