# Generated by Django 6.0 on 2026-04-08 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0010_mappin_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappin',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='mappin',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='mappin',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='mappin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_pins', to=settings.AUTH_USER_MODEL),
        ),
    ]
