# Generated by Django 6.0 on 2026-02-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
