# Generated by Django 6.0 on 2026-01-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
