# Generated by Django 6.0 on 2026-03-21 12:37

import plans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plansharemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansharemember',
            name='expires_at',
            field=models.DateTimeField(default=plans.models.default_expires_at),
        ),
    ]
