# Generated by Django 6.0 on 2026-01-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_dayschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayschedule',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
