# Generated by Django 6.0 on 2026-04-06 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plansharemember_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.schedule'),
        ),
    ]
