# Generated by Django 6.0 on 2026-02-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
